// <auto-generated />
using System;
using Back;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(BancoDbContextcs))]
    [Migration("20231011191530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back.Clases.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Back.Clases.CuentaBancaria", b =>
                {
                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Saldo")
                        .HasColumnType("float");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("Titular_CuentaIdCliente")
                        .HasColumnType("int");

                    b.HasKey("NumeroCuenta");

                    b.HasIndex("Titular_CuentaIdCliente");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("Back.Clases.TarjetaDeCredito", b =>
                {
                    b.Property<int>("NumeroTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroTarjeta"));

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<double?>("LimiteCredito")
                        .HasColumnType("float");

                    b.Property<double?>("MontoDeuda")
                        .HasColumnType("float");

                    b.Property<string>("NombreTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Saldo")
                        .HasColumnType("float");

                    b.Property<int?>("TitularIdCliente")
                        .HasColumnType("int");

                    b.HasKey("NumeroTarjeta");

                    b.HasIndex("TitularIdCliente");

                    b.ToTable("TarjetasDeCredito");
                });

            modelBuilder.Entity("Back.Clases.CuentaBancaria", b =>
                {
                    b.HasOne("Back.Clases.Cliente", "Titular_Cuenta")
                        .WithMany()
                        .HasForeignKey("Titular_CuentaIdCliente");

                    b.Navigation("Titular_Cuenta");
                });

            modelBuilder.Entity("Back.Clases.TarjetaDeCredito", b =>
                {
                    b.HasOne("Back.Clases.Cliente", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularIdCliente");

                    b.Navigation("Titular");
                });
#pragma warning restore 612, 618
        }
    }
}
